# Generated by Django 4.1 on 2022-10-05 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("FuerzasMilitares", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModeloVehiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color", models.CharField(max_length=20)),
                ("tipo", models.CharField(max_length=100)),
                ("capacidad", models.IntegerField(default=2)),
                ("blindado", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ModeloVisitante",
            fields=[
                (
                    "datosbasicos_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="FuerzasMilitares.datosbasicos",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("motivo", models.TextField(blank=True, max_length=300, null=True)),
            ],
            bases=("FuerzasMilitares.datosbasicos",),
        ),
        migrations.CreateModel(
            name="Vehiculo",
            fields=[
                (
                    "modelovehiculo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="AppSeguridad.modelovehiculo",
                    ),
                ),
                (
                    "placa",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                (
                    "modelo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modelo_vehiculo_visitante",
                        to="AppSeguridad.modelovehiculo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehiculo",
                "verbose_name_plural": "Vehiculos",
            },
            bases=("AppSeguridad.modelovehiculo",),
        ),
        migrations.CreateModel(
            name="IntegranteEsquemaSeguridad",
            fields=[
                ("id_integrante", models.AutoField(primary_key=True, serialize=False)),
                (
                    "arma",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrate_esquema_arma",
                        to="FuerzasMilitares.arma",
                    ),
                ),
                (
                    "militar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrate_esquema_militar",
                        to="FuerzasMilitares.militar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Integrante de esquema de seguridad",
                "verbose_name_plural": "Integrantes de esquema de seguridad",
            },
        ),
        migrations.CreateModel(
            name="EsquemaSeguridad",
            fields=[
                (
                    "id_esquema_seguridad",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=255)),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        help_text="Descripcion de esquema de seguridad",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "instalacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="esquema_instalacion",
                        to="FuerzasMilitares.instalacionmilitar",
                    ),
                ),
                (
                    "integrante",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="esquema_integrante",
                        to="AppSeguridad.integranteesquemaseguridad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Esquema de seguridad",
                "verbose_name_plural": "Esquemas de seguridad",
            },
        ),
        migrations.CreateModel(
            name="Visitante",
            fields=[
                (
                    "datosbasicos_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="FuerzasMilitares.datosbasicos",
                    ),
                ),
                (
                    "vehiculo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visitante_vehiculo",
                        to="AppSeguridad.vehiculo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Visitante",
                "verbose_name_plural": "Visitantes",
            },
            bases=("FuerzasMilitares.datosbasicos",),
        ),
    ]
