# Generated by Django 4.1 on 2022-09-22 17:32

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DatosBasicos",
            fields=[
                (
                    "id_datos_basicos",
                    models.AutoField(default=None, primary_key=True, serialize=False),
                ),
                ("nombres", models.CharField(max_length=30)),
                ("apellidos", models.CharField(max_length=30)),
                ("correo_electronico", models.EmailField(max_length=30)),
                (
                    "tipo_sangre",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        default=("O+", "O+"),
                        max_length=3,
                    ),
                ),
                ("numero_cedula", models.CharField(max_length=15)),
                ("fecha_nacimiento", models.DateField(null=True)),
                (
                    "numero_telefono",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region=None, unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModeloArma",
            fields=[
                ("id_modelo_arma", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("calibre", models.CharField(max_length=10)),
                (
                    "observacion",
                    models.TextField(
                        blank=True,
                        default="No presenta novedades",
                        max_length=230,
                        null=True,
                    ),
                ),
                ("letal", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ModeloInstalacion",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("departamento", models.CharField(max_length=150)),
                ("municipio", models.CharField(max_length=150)),
                (
                    "ubicacion_latitud",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                (
                    "ubicacion_longitud",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModeloVehiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color", models.CharField(max_length=20)),
                ("tipo", models.CharField(max_length=100)),
                ("capacidad", models.IntegerField(default=2)),
                ("blindado", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ModeloVisitante",
            fields=[
                (
                    "datosbasicos_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="AppSeguridad.datosbasicos",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("motivo", models.TextField(blank=True, max_length=300, null=True)),
            ],
            bases=("AppSeguridad.datosbasicos",),
        ),
        migrations.CreateModel(
            name="Visitante",
            fields=[
                (
                    "datosbasicos_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="AppSeguridad.datosbasicos",
                    ),
                ),
                (
                    "id_visitante",
                    models.AutoField(default=None, primary_key=True, serialize=False),
                ),
            ],
            bases=("AppSeguridad.datosbasicos",),
        ),
        migrations.CreateModel(
            name="Arma",
            fields=[
                (
                    "serial",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                (
                    "modelo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modelo_arma",
                        to="AppSeguridad.modeloarma",
                    ),
                ),
            ],
        ),
    ]
