# Generated by Django 4.1 on 2022-08-24 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("AppSeguridad", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Arma",
            fields=[
                ("id_arma", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="datospersonales",
            name="copia_cedula",
            field=models.FileField(upload_to="media\\images\\cedulas"),
        ),
        migrations.AlterField(
            model_name="datospersonales",
            name="foto",
            field=models.ImageField(upload_to="media\\images\\fotos"),
        ),
        migrations.AlterField(
            model_name="datospersonales",
            name="tipo_sangre",
            field=models.CharField(
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                ],
                default=("A+", "A+"),
                max_length=3,
            ),
        ),
        migrations.CreateModel(
            name="ArmaLetal",
            fields=[
                (
                    "arma_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="AppSeguridad.arma",
                    ),
                ),
                ("id_arma_letal", models.AutoField(primary_key=True, serialize=False)),
                ("calibre", models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            bases=("AppSeguridad.arma",),
        ),
    ]
