# Generated by Django 4.1 on 2022-10-03 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("FuerzasMilitares", "0003_remove_ubicacionmilitar_batallon_and_more"),
        ("AppSeguridad", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="esquemaseguridad",
            name="batallon",
        ),
        migrations.RemoveField(
            model_name="esquemaseguridad",
            name="brigada",
        ),
        migrations.RemoveField(
            model_name="esquemaseguridad",
            name="planos",
        ),
        migrations.AddField(
            model_name="esquemaseguridad",
            name="instalacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="esquema_instalacion",
                to="FuerzasMilitares.instalacionmilitar",
            ),
        ),
    ]
