# Generated by Django 4.1 on 2022-10-05 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AppSeguridad", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="modelovehiculo",
            options={
                "verbose_name": "Modelo de vehiculo",
                "verbose_name_plural": "Modelos de vehiculos",
            },
        ),
        migrations.AlterModelTable(
            name="esquemaseguridad",
            table="esquema_seguridad",
        ),
        migrations.AlterModelTable(
            name="integranteesquemaseguridad",
            table="integrante_esquema_seguridad",
        ),
        migrations.AlterModelTable(
            name="modelovehiculo",
            table="modelo_vehiculo",
        ),
        migrations.AlterModelTable(
            name="vehiculo",
            table="vehiculo",
        ),
        migrations.AlterModelTable(
            name="visitante",
            table="visitante",
        ),
    ]
