# Generated by Django 4.1 on 2022-08-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppSeguridad", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="arma",
            name="letal",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="datospersonales",
            name="copia_cedula",
            field=models.FileField(upload_to="\\images\\cedulas"),
        ),
        migrations.AlterField(
            model_name="datospersonales",
            name="foto",
            field=models.ImageField(upload_to="\\images\\fotos"),
        ),
        migrations.AlterField(
            model_name="datospersonales",
            name="libreta_militar",
            field=models.FileField(
                blank=True, null=True, upload_to="\\images\\libreta_militar"
            ),
        ),
        migrations.AlterField(
            model_name="datospersonales",
            name="licencia_conduccion",
            field=models.FileField(
                blank=True, null=True, upload_to="\\images\\licencias"
            ),
        ),
        migrations.AlterField(
            model_name="datospersonales",
            name="salvo_conducto_armas",
            field=models.FileField(
                blank=True, null=True, upload_to="\\images\\salvo_conducto_armas"
            ),
        ),
    ]
