# Generated by Django 4.1 on 2022-10-05 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AppSeguridad", "0002_alter_modelovehiculo_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="modelovisitante",
            options={
                "verbose_name": "Modelo de visitante",
                "verbose_name_plural": "Modelos de visitantes",
            },
        ),
        migrations.AlterModelTable(
            name="modelovisitante",
            table="modelo_visitante",
        ),
    ]
