# Generated by Django 4.1 on 2022-08-24 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("AppSeguridad", "0002_arma_letal_alter_datospersonales_copia_cedula_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datospersonales",
            name="copia_cedula",
            field=models.FileField(upload_to="archivos\\cedulas"),
        ),
        migrations.AlterField(
            model_name="datospersonales",
            name="foto",
            field=models.ImageField(upload_to="images\\fotos"),
        ),
        migrations.AlterField(
            model_name="datospersonales",
            name="libreta_militar",
            field=models.FileField(
                blank=True, null=True, upload_to="archivos\\libreta_militar"
            ),
        ),
        migrations.AlterField(
            model_name="datospersonales",
            name="licencia_conduccion",
            field=models.FileField(
                blank=True, null=True, upload_to="archivos\\licencias"
            ),
        ),
        migrations.AlterField(
            model_name="datospersonales",
            name="salvo_conducto_armas",
            field=models.FileField(
                blank=True, null=True, upload_to="archivos\\salvo_conducto_armas"
            ),
        ),
        migrations.CreateModel(
            name="Escolta",
            fields=[
                (
                    "datospersonales_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="AppSeguridad.datospersonales",
                    ),
                ),
                ("id_escolta", models.AutoField(primary_key=True, serialize=False)),
                (
                    "arma",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppSeguridad.arma",
                    ),
                ),
            ],
            bases=("AppSeguridad.datospersonales",),
        ),
    ]
