# Generated by Django 4.1 on 2022-09-22 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AppSeguridad", "0003_remove_visitante_id_visitante_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Arma",
        ),
        migrations.DeleteModel(
            name="ModeloArma",
        ),
    ]
