# Generated by Django 4.0.5 on 2022-08-24 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSeguridad', '0003_alter_datospersonales_copia_cedula_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instalacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion_Latitud', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ubicacion_longitud', models.DecimalField(decimal_places=2, max_digits=15)),
                ('numero_plantas', models.IntegerField(blank=True, default=1)),
                ('direccion', models.CharField(blank=True, max_length=30)),
                ('descipcion', models.CharField(blank=True, max_length=100)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('planos', models.FileField(blank=True, upload_to='archivos\\planos')),
            ],
        ),
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('id_posicion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('piso', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='arma',
            name='id_arma',
        ),
        migrations.AlterField(
            model_name='arma',
            name='observacion',
            field=models.TextField(blank=True, default='Sin novedad', max_length=230),
        ),
        migrations.AlterField(
            model_name='arma',
            name='serial',
            field=models.CharField(default='Sin registrar', max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='tipo_sangre',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default=('O+', 'O+'), max_length=3),
        ),
    ]
