# Generated by Django 4.1 on 2022-09-22 18:31

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("AppSeguridad", "0004_delete_arma_delete_modeloarma"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datosbasicos",
            name="fecha_nacimiento",
            field=models.DateField(
                help_text="Por favor ingrese una fecha con el formato AAAA-MM-DD",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="datosbasicos",
            name="numero_telefono",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="Indicativo de Colombia +57",
                max_length=128,
                null=True,
                region=None,
            ),
        ),
    ]
