# Generated by Django 4.1 on 2022-08-26 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("AppSeguridad", "0004_instalacion_posicion_remove_arma_id_arma_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instalacion",
            name="id",
        ),
        migrations.AlterField(
            model_name="instalacion",
            name="nombre",
            field=models.CharField(
                blank=True, max_length=100, primary_key=True, serialize=False
            ),
        ),
        migrations.CreateModel(
            name="EsquemaProteccion",
            fields=[
                ("fecha", models.DateField(auto_created=True)),
                (
                    "id_esquema_proteccion",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "escoltas",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppSeguridad.escolta",
                    ),
                ),
                (
                    "instalacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppSeguridad.instalacion",
                    ),
                ),
            ],
        ),
    ]
