# Generated by Django 4.1 on 2022-11-08 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AppSeguridad", "0004_visitante_datos_entrada_visitante_motivo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ModeloVisitante",
        ),
    ]
