# Generated by Django 4.1 on 2022-09-08 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "AppSeguridad",
            "0005_remove_instalacion_id_alter_instalacion_nombre_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Batallon",
            fields=[
                (
                    "nombre",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                (
                    "ubicacion_latitud",
                    models.DecimalField(decimal_places=15, max_digits=30),
                ),
                (
                    "tipo_fuerza",
                    models.CharField(
                        choices=[
                            (
                                "Ejercito Nacional de Colombia",
                                "Ejercito Nacional de Colombia",
                            ),
                            (
                                "Armada de la República de Colombia",
                                "Armada de la República de Colombia",
                            ),
                        ],
                        default=(
                            "Ejercito Nacional de Colombia",
                            "Ejercito Nacional de Colombia",
                        ),
                        max_length=50,
                    ),
                ),
                (
                    "ubicacion_longitud",
                    models.DecimalField(decimal_places=15, max_digits=30),
                ),
                ("direccion", models.CharField(blank=True, max_length=30)),
                ("ciudad", models.CharField(blank=True, max_length=50)),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("planos", models.FileField(blank=True, upload_to="archivos\\planos")),
            ],
        ),
        migrations.CreateModel(
            name="DatosBasicos",
            fields=[
                ("nombres", models.CharField(blank=True, max_length=30)),
                ("apellidos", models.CharField(blank=True, max_length=30)),
                ("correo_electronico", models.EmailField(blank=True, max_length=30)),
                (
                    "tipo_sangre",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        default=("O+", "O+"),
                        max_length=3,
                    ),
                ),
                (
                    "numero_cedula",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Poligono",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("fecha", models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name="escolta",
            name="arma",
        ),
        migrations.RemoveField(
            model_name="escolta",
            name="datospersonales_ptr",
        ),
        migrations.RemoveField(
            model_name="esquemaproteccion",
            name="escoltas",
        ),
        migrations.RemoveField(
            model_name="esquemaproteccion",
            name="instalacion",
        ),
        migrations.RemoveField(
            model_name="protegido",
            name="datospersonales_ptr",
        ),
        migrations.AlterField(
            model_name="arma",
            name="calibre",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="arma",
            name="serial",
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name="DatosMilitar",
            fields=[
                (
                    "datosbasicos_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="AppSeguridad.datosbasicos",
                    ),
                ),
                ("copia_cedula", models.FileField(upload_to="archivos\\cedulas")),
                ("foto", models.ImageField(upload_to="images\\fotos")),
                (
                    "salvo_conducto_armas",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="archivos\\salvo_conducto_armas",
                    ),
                ),
                (
                    "licencia_conduccion",
                    models.FileField(
                        blank=True, null=True, upload_to="archivos\\licencias"
                    ),
                ),
                (
                    "libreta_militar",
                    models.FileField(
                        blank=True, null=True, upload_to="archivos\\libreta_militar"
                    ),
                ),
            ],
            bases=("AppSeguridad.datosbasicos",),
        ),
        migrations.CreateModel(
            name="Visitante",
            fields=[
                (
                    "datosbasicos_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="AppSeguridad.datosbasicos",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("direccion", models.CharField(blank=True, max_length=50, null=True)),
            ],
            bases=("AppSeguridad.datosbasicos",),
        ),
        migrations.DeleteModel(
            name="DatosPersonales",
        ),
        migrations.DeleteModel(
            name="Escolta",
        ),
        migrations.DeleteModel(
            name="EsquemaProteccion",
        ),
        migrations.DeleteModel(
            name="Instalacion",
        ),
        migrations.DeleteModel(
            name="Protegido",
        ),
        migrations.CreateModel(
            name="Militar",
            fields=[
                (
                    "datosmilitar_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="AppSeguridad.datosmilitar",
                    ),
                ),
                (
                    "grado",
                    models.CharField(
                        choices=[
                            ("Oficial", "Oficial"),
                            ("Suboficial", "Suboficial"),
                            ("Soldado profesional", "Soldado profesional"),
                            ("Soldado raso", "Soldado raso"),
                        ],
                        default=("Soldado profesional", "Soldado profesional"),
                        max_length=20,
                    ),
                ),
                (
                    "arma",
                    models.OneToOneField(
                        blank=True,
                        default="Sin registrar",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppSeguridad.arma",
                    ),
                ),
                (
                    "poligonos",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppSeguridad.poligono",
                    ),
                ),
                (
                    "posicion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppSeguridad.posicion",
                    ),
                ),
            ],
            bases=("AppSeguridad.datosmilitar",),
        ),
    ]
