# Generated by Django 4.1 on 2022-09-22 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("FuerzasMilitares", "0005_alter_arma_fuerza_militar_alter_arma_modelo"),
        ("AppSeguridad", "0005_alter_datosbasicos_fecha_nacimiento_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EsquemaSeguridad",
            fields=[
                (
                    "id_esquema_seguridad",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=255)),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        help_text="Descripcion de esquema de seguridad",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "planos",
                    models.FileField(
                        blank=True,
                        help_text="Planos de la instalación en formato .svg",
                        null=True,
                        upload_to="archivos\\planos",
                    ),
                ),
            ],
            options={
                "verbose_name": "Esquema de seguridad",
                "verbose_name_plural": "Esquemas de seguridad",
            },
        ),
        migrations.CreateModel(
            name="Vehiculo",
            fields=[
                (
                    "modelovehiculo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="AppSeguridad.modelovehiculo",
                    ),
                ),
                (
                    "placa",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                (
                    "modelo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modelo_vehiculo_visitante",
                        to="AppSeguridad.modelovehiculo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehiculo",
                "verbose_name_plural": "Vehiculos",
            },
            bases=("AppSeguridad.modelovehiculo",),
        ),
        migrations.CreateModel(
            name="IntegranteEsquemaSeguridad",
            fields=[
                ("id_integrante", models.AutoField(primary_key=True, serialize=False)),
                (
                    "arma",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrate_esquema_arma",
                        to="FuerzasMilitares.arma",
                    ),
                ),
                (
                    "militar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrate_esquema_militar",
                        to="FuerzasMilitares.militar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Integrante de esquema de seguridad",
                "verbose_name_plural": "Integrantes de esquema de seguridad",
            },
        ),
    ]
