# Generated by Django 4.1 on 2022-11-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppSeguridad", "0005_delete_modelovisitante"),
    ]

    operations = [
        migrations.AddField(
            model_name="integranteesquemaseguridad",
            name="tarea",
            field=models.CharField(blank=True, default="No asignada", max_length=200),
        ),
    ]
