# Generated by Django 4.1 on 2022-09-22 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("FuerzasMilitares", "0006_divisionmilitar_brigadamilitar_batallon"),
        ("AppSeguridad", "0006_esquemaseguridad_vehiculo_integranteesquemaseguridad"),
    ]

    operations = [
        migrations.AddField(
            model_name="esquemaseguridad",
            name="batallon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="esquema_batallon",
                to="FuerzasMilitares.batallon",
            ),
        ),
        migrations.AddField(
            model_name="esquemaseguridad",
            name="brigada",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="esquema_brigada",
                to="FuerzasMilitares.brigadamilitar",
            ),
        ),
        migrations.AddField(
            model_name="esquemaseguridad",
            name="integrante",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="esquema_integrante",
                to="AppSeguridad.integranteesquemaseguridad",
            ),
        ),
    ]
