# Generated by Django 4.1 on 2022-11-13 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppSeguridad", "0006_integranteesquemaseguridad_tarea"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integranteesquemaseguridad",
            name="tarea",
            field=models.TextField(blank=True, default="", max_length=200),
        ),
    ]
