# Generated by Django 4.1 on 2022-09-14 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("FuerzasMilitares", "0001_initial"),
        ("AppSeguridad", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="BatallonEjercito",
            fields=[
                (
                    "modelobrigadabatallonmilitar_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="AppSeguridad.modelobrigadabatallonmilitar",
                    ),
                ),
            ],
            bases=("AppSeguridad.modelobrigadabatallonmilitar",),
        ),
        migrations.CreateModel(
            name="BrigadaUnidadEjercitoNacional",
            fields=[
                (
                    "modelobrigadabatallonmilitar_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="AppSeguridad.modelobrigadabatallonmilitar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Brigada de Ejercito Nacional",
                "verbose_name_plural": "Brigadas de Ejercito Nacional",
            },
            bases=("AppSeguridad.modelobrigadabatallonmilitar",),
        ),
        migrations.CreateModel(
            name="DivisonMilitar",
            fields=[
                (
                    "nombre",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("logo", models.ImageField(upload_to="images\\divisiones_militares")),
                (
                    "fuerza_militar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuerza_militar_divison",
                        to="FuerzasMilitares.fuerzasmilitares",
                    ),
                ),
            ],
            options={
                "verbose_name": "Division Militar",
                "verbose_name_plural": "Divisiones Militares",
            },
        ),
        migrations.CreateModel(
            name="DivisonEjercitoNacional",
            fields=[
                (
                    "divisonmilitar_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="EjercitoNacional.divisonmilitar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Divison de Ejercito Nacional",
                "verbose_name_plural": "Divisones de Ejercito Nacional",
            },
            bases=("EjercitoNacional.divisonmilitar",),
        ),
        migrations.CreateModel(
            name="MilitarEjercito",
            fields=[
                (
                    "datosmilitar_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="AppSeguridad.datosmilitar",
                    ),
                ),
                (
                    "arma",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppSeguridad.arma",
                    ),
                ),
                (
                    "batallon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batallon_militar_ejercito",
                        to="EjercitoNacional.batallonejercito",
                    ),
                ),
                (
                    "posicion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppSeguridad.posicionesquemaseguridad",
                    ),
                ),
            ],
            bases=("AppSeguridad.datosmilitar",),
        ),
        migrations.AddField(
            model_name="batallonejercito",
            name="brigada",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="brigada_batallon_ejercito",
                to="EjercitoNacional.brigadaunidadejercitonacional",
            ),
        ),
        migrations.AddField(
            model_name="brigadaunidadejercitonacional",
            name="division",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="division_brigada_ejercito",
                to="EjercitoNacional.divisonejercitonacional",
            ),
        ),
    ]
