# Generated by Django 4.1 on 2022-09-14 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("EjercitoNacional", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="batallonejercito",
            options={
                "verbose_name": "Batallond de Ejercito Nacional",
                "verbose_name_plural": "Batallones de Ejercito nacional",
            },
        ),
        migrations.AlterModelOptions(
            name="militarejercito",
            options={
                "verbose_name": "Militar de Ejercito Nacional",
                "verbose_name_plural": "Militares de Ejercito Nacional",
            },
        ),
    ]
