# Generated by Django 4.1 on 2022-09-14 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("AppSeguridad", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="BatallonInfanteria",
            fields=[
                (
                    "modelobrigadabatallonmilitar_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="AppSeguridad.modelobrigadabatallonmilitar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Batallon de Infanteria de Marina",
                "verbose_name_plural": "Batallones de Infanteria de Marina",
            },
            bases=("AppSeguridad.modelobrigadabatallonmilitar",),
        ),
        migrations.CreateModel(
            name="BrigadaArmadaNacional",
            fields=[
                (
                    "modelobrigadabatallonmilitar_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="AppSeguridad.modelobrigadabatallonmilitar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Brigada de Infanteria de Marina",
                "verbose_name_plural": "Brigadas de Infanteria de Marina",
            },
            bases=("AppSeguridad.modelobrigadabatallonmilitar",),
        ),
        migrations.CreateModel(
            name="InfanteMarina",
            fields=[
                (
                    "datosmilitar_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="AppSeguridad.datosmilitar",
                    ),
                ),
                (
                    "batallon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batallon_infanteria_marina",
                        to="ArmadaNacional.batalloninfanteria",
                    ),
                ),
            ],
            bases=("AppSeguridad.datosmilitar",),
        ),
        migrations.AddField(
            model_name="batalloninfanteria",
            name="brigada",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="brigada_batallon",
                to="ArmadaNacional.brigadaarmadanacional",
            ),
        ),
    ]
