# Generated by Django 4.1 on 2022-09-14 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ArmadaNacional", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="infantemarina",
            options={
                "verbose_name": "Infante de marina",
                "verbose_name_plural": "Infantes de marina",
            },
        ),
    ]
