# Generated by Django 4.1 on 2022-09-22 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("AppSeguridad", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="FuerzaMilitar",
            fields=[
                ("id_fuerza", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=150, unique=True)),
                ("logo", models.ImageField(upload_to="images\\fuerzas_militares")),
            ],
            options={
                "verbose_name": "Fuerza Militar",
                "verbose_name_plural": "Fuerzas Militares",
            },
        ),
        migrations.CreateModel(
            name="RangoMilitar",
            fields=[
                ("id_rango", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre de fuerza militar",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "abreviatura",
                    models.CharField(
                        blank=True,
                        help_text="Abreviatura del rango militar",
                        max_length=15,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        help_text="Logo de rango", upload_to="images\\grados_militares"
                    ),
                ),
                (
                    "fuerza_militar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="FuerzasMilitares.fuerzamilitar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rango militar",
                "verbose_name_plural": "Rangos militares",
            },
        ),
        migrations.CreateModel(
            name="Militar",
            fields=[
                (
                    "datosbasicos_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="AppSeguridad.datosbasicos",
                    ),
                ),
                ("id_militar", models.AutoField(primary_key=True, serialize=False)),
                (
                    "copia_cedula",
                    models.FileField(
                        blank=True, null=True, upload_to="archivos\\cedulas"
                    ),
                ),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="images\\fotos"),
                ),
                ("disponible", models.BooleanField(default=True)),
                (
                    "rango",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rango_militar",
                        to="FuerzasMilitares.rangomilitar",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usuario_militar",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Militar",
                "verbose_name_plural": "Militares",
            },
            bases=("AppSeguridad.datosbasicos",),
        ),
    ]
