# Generated by Django 4.1 on 2022-09-24 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DatosBasicos",
            fields=[
                (
                    "id_datos_basicos",
                    models.AutoField(default=None, primary_key=True, serialize=False),
                ),
                ("nombres", models.CharField(max_length=30)),
                ("apellidos", models.CharField(max_length=30)),
                ("correo_electronico", models.EmailField(max_length=30)),
                (
                    "tipo_sangre",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        default=("O+", "O+"),
                        max_length=3,
                    ),
                ),
                ("numero_cedula", models.CharField(max_length=15)),
                (
                    "fecha_nacimiento",
                    models.DateField(
                        help_text="Por favor ingrese una fecha con el formato AAAA-MM-DD",
                        null=True,
                    ),
                ),
                (
                    "numero_telefono",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        help_text="Indicativo de Colombia +57",
                        max_length=128,
                        null=True,
                        region=None,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FuerzaMilitar",
            fields=[
                ("id_fuerza", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=150, unique=True)),
                ("logo", models.ImageField(upload_to="images\\fuerzas_militares")),
            ],
            options={
                "verbose_name": "Fuerza Militar",
                "verbose_name_plural": "Fuerzas Militares",
            },
        ),
        migrations.CreateModel(
            name="ModeloArma",
            fields=[
                ("id_modelo_arma", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("calibre", models.CharField(max_length=10)),
                (
                    "observacion",
                    models.TextField(
                        blank=True,
                        default="No presenta novedades",
                        max_length=230,
                        null=True,
                    ),
                ),
                ("letal", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Modelo de arma",
                "verbose_name_plural": "Modelos de armas",
            },
        ),
        migrations.CreateModel(
            name="ModeloInstalacion",
            fields=[
                (
                    "id_modelo_instalacion",
                    models.AutoField(default=None, primary_key=True, serialize=False),
                ),
                ("departamento", models.CharField(max_length=150)),
                ("municipio", models.CharField(max_length=150)),
                (
                    "ubicacion_latitud",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                (
                    "ubicacion_longitud",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RangoMilitar",
            fields=[
                ("id_rango", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre de fuerza militar",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "abreviatura",
                    models.CharField(
                        blank=True,
                        help_text="Abreviatura del rango militar",
                        max_length=15,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        help_text="Logo de rango", upload_to="images\\grados_militares"
                    ),
                ),
                (
                    "fuerza_militar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="FuerzasMilitares.fuerzamilitar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rango militar",
                "verbose_name_plural": "Rangos militares",
            },
        ),
        migrations.CreateModel(
            name="DivisionMilitar",
            fields=[
                ("id_division", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=255)),
                ("logo", models.ImageField(upload_to="images\\divisiones_militares")),
                (
                    "fuerza_militar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuerzamilitar_division",
                        to="FuerzasMilitares.fuerzamilitar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Division militar",
                "verbose_name_plural": "Divisiones militares",
            },
        ),
        migrations.CreateModel(
            name="Arma",
            fields=[
                (
                    "serial",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                (
                    "fuerza_militar",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modelo_arma_fuerza_militar",
                        to="FuerzasMilitares.fuerzamilitar",
                    ),
                ),
                (
                    "modelo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modelo_arma",
                        to="FuerzasMilitares.modeloarma",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Militar",
            fields=[
                (
                    "datosbasicos_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="FuerzasMilitares.datosbasicos",
                    ),
                ),
                ("id_militar", models.AutoField(primary_key=True, serialize=False)),
                (
                    "copia_cedula",
                    models.FileField(
                        blank=True, null=True, upload_to="archivos\\cedulas"
                    ),
                ),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="images\\fotos"),
                ),
                (
                    "grado",
                    models.CharField(
                        choices=[
                            ("SubOficial", "SubOficial"),
                            ("Oficial", "Oficial"),
                            ("Soldado Profesional", "Soldado Profesional"),
                        ],
                        default=("SubOficial", "SubOficial"),
                        max_length=20,
                    ),
                ),
                ("disponible", models.BooleanField(default=True)),
                (
                    "rango",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rango_militar",
                        to="FuerzasMilitares.rangomilitar",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usuario_militar",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Militar",
                "verbose_name_plural": "Militares",
            },
            bases=("FuerzasMilitares.datosbasicos",),
        ),
        migrations.CreateModel(
            name="BrigadaMilitar",
            fields=[
                (
                    "modeloinstalacion_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="FuerzasMilitares.modeloinstalacion",
                    ),
                ),
                ("id_brigada", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=255)),
                ("logo", models.ImageField(upload_to="images\\brigadas_militares")),
                (
                    "division",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="division_brigada",
                        to="FuerzasMilitares.divisionmilitar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Brigada militar",
                "verbose_name_plural": "Brigadas militares",
            },
            bases=("FuerzasMilitares.modeloinstalacion",),
        ),
        migrations.CreateModel(
            name="Batallon",
            fields=[
                (
                    "modeloinstalacion_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="FuerzasMilitares.modeloinstalacion",
                    ),
                ),
                ("id_batallon", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=255)),
                ("logo", models.ImageField(upload_to="images\\batallones")),
                (
                    "brigada",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batallon_militar",
                        to="FuerzasMilitares.brigadamilitar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Batallon",
                "verbose_name_plural": "Batallones",
            },
            bases=("FuerzasMilitares.modeloinstalacion",),
        ),
    ]
