# Generated by Django 4.1 on 2022-09-14 08:20

import django.core.management.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("FuerzasMilitares", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TokenAcceso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=django.core.management.utils.get_random_secret_key,
                        max_length=255,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="fuerzasmilitares",
            name="token_acceso",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="FuerzasMilitares.tokenacceso",
                verbose_name="token_fuerza_militar",
            ),
        ),
    ]
