# Generated by Django 4.1 on 2022-09-22 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("FuerzasMilitares", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModeloArma",
            fields=[
                ("id_modelo_arma", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("calibre", models.CharField(max_length=10)),
                (
                    "observacion",
                    models.TextField(
                        blank=True,
                        default="No presenta novedades",
                        max_length=230,
                        null=True,
                    ),
                ),
                ("letal", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Modelo de arma",
                "verbose_name_plural": "Modelos de armas",
            },
        ),
        migrations.CreateModel(
            name="Arma",
            fields=[
                (
                    "serial",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                (
                    "modelo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modelo_arma",
                        to="FuerzasMilitares.modeloarma",
                    ),
                ),
            ],
        ),
    ]
