# Generated by Django 4.1 on 2022-10-05 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("FuerzasMilitares", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="practicapoligono",
            table="practica_poligono",
        ),
    ]
