# Generated by Django 4.1 on 2022-09-26 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("FuerzasMilitares", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batallon",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="images\\batallones"
            ),
        ),
        migrations.CreateModel(
            name="UbicacionMilitar",
            fields=[
                ("id_ubicacion", models.AutoField(primary_key=True, serialize=False)),
                (
                    "batallon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ubicacion_militar_batallon",
                        to="FuerzasMilitares.batallon",
                    ),
                ),
                (
                    "brigada",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ubicacacion_militar_brigada",
                        to="FuerzasMilitares.brigadamilitar",
                    ),
                ),
                (
                    "militar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ubicacacion_militar",
                        to="FuerzasMilitares.militar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ubicacion Militar",
                "verbose_name_plural": "Ubicaciones de Militares",
            },
        ),
    ]
