# Generated by Django 4.1 on 2022-09-14 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("FuerzasMilitares", "0002_tokenacceso_fuerzasmilitares_token_acceso"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fuerzasmilitares",
            name="token_acceso",
        ),
        migrations.DeleteModel(
            name="TokenAcceso",
        ),
    ]
