# Generated by Django 4.1 on 2022-10-03 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("FuerzasMilitares", "0002_alter_batallon_logo_ubicacionmilitar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ubicacionmilitar",
            name="batallon",
        ),
        migrations.RemoveField(
            model_name="ubicacionmilitar",
            name="brigada",
        ),
        migrations.AlterField(
            model_name="brigadamilitar",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="images\\brigadas_militares"
            ),
        ),
        migrations.CreateModel(
            name="InstalacionMilitar",
            fields=[
                (
                    "modeloinstalacion_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="FuerzasMilitares.modeloinstalacion",
                    ),
                ),
                ("id_instalacion", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=255)),
                (
                    "planos",
                    models.FileField(
                        blank=True,
                        help_text="Planos de la instalación en formato .svg",
                        null=True,
                        upload_to="archivos\\planos",
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="division_instalacion",
                        to="FuerzasMilitares.divisionmilitar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instalación militar",
                "verbose_name_plural": "Instalaciones militares",
            },
            bases=("FuerzasMilitares.modeloinstalacion",),
        ),
        migrations.AddField(
            model_name="ubicacionmilitar",
            name="instalacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ubicacacion_militar_instalacion",
                to="FuerzasMilitares.instalacionmilitar",
            ),
        ),
    ]
