# Generated by Django 4.1 on 2022-09-14 13:45

import django.core.management.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FuerzasMilitares", "0003_remove_fuerzasmilitares_token_acceso_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fuerzasmilitares",
            options={},
        ),
        migrations.AddField(
            model_name="fuerzasmilitares",
            name="token_acceso",
            field=models.CharField(
                blank=True,
                default=django.core.management.utils.get_random_secret_key,
                max_length=255,
                null=True,
            ),
        ),
    ]
