# Generated by Django 4.1 on 2022-10-05 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "FuerzasMilitares",
            "0003_alter_arma_options_alter_modeloarma_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelTable(
            name="rangomilitar",
            table="rango_militar",
        ),
        migrations.AlterModelTable(
            name="ubicacionmilitar",
            table="ubicacacion_militar",
        ),
    ]
