# Generated by Django 4.1 on 2022-10-05 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("FuerzasMilitares", "0004_alter_rangomilitar_table_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="modeloinstalacion",
            name="ubicacion_latitud",
        ),
        migrations.RemoveField(
            model_name="modeloinstalacion",
            name="ubicacion_longitud",
        ),
    ]
