# Generated by Django 4.1 on 2022-09-22 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "FuerzasMilitares",
            "0004_remove_modeloarma_fuerza_militar_arma_fuerza_militar",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="arma",
            name="fuerza_militar",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modelo_arma_fuerza_militar",
                to="FuerzasMilitares.fuerzamilitar",
            ),
        ),
        migrations.AlterField(
            model_name="arma",
            name="modelo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modelo_arma",
                to="FuerzasMilitares.modeloarma",
            ),
        ),
    ]
