# Generated by Django 4.1 on 2022-09-22 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("AppSeguridad", "0006_esquemaseguridad_vehiculo_integranteesquemaseguridad"),
        ("FuerzasMilitares", "0005_alter_arma_fuerza_militar_alter_arma_modelo"),
    ]

    operations = [
        migrations.CreateModel(
            name="DivisionMilitar",
            fields=[
                ("id_division", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=255)),
                ("logo", models.ImageField(upload_to="images\\divisiones_militares")),
                (
                    "fuerza_militar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuerzamilitar_division",
                        to="FuerzasMilitares.fuerzamilitar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Division militar",
                "verbose_name_plural": "Divisiones militares",
            },
        ),
        migrations.CreateModel(
            name="BrigadaMilitar",
            fields=[
                (
                    "modeloinstalacion_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="AppSeguridad.modeloinstalacion",
                    ),
                ),
                ("id_brigada", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=255)),
                ("logo", models.ImageField(upload_to="images\\brigadas_militares")),
                (
                    "division",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="division_brigada",
                        to="FuerzasMilitares.divisionmilitar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Brigada militar",
                "verbose_name_plural": "Brigadas militares",
            },
            bases=("AppSeguridad.modeloinstalacion",),
        ),
        migrations.CreateModel(
            name="Batallon",
            fields=[
                (
                    "modeloinstalacion_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="AppSeguridad.modeloinstalacion",
                    ),
                ),
                ("id_batallon", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=255)),
                ("logo", models.ImageField(upload_to="images\\batallones")),
                (
                    "brigada",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batallon_militar",
                        to="FuerzasMilitares.brigadamilitar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Batallon",
                "verbose_name_plural": "Batallones",
            },
            bases=("AppSeguridad.modeloinstalacion",),
        ),
    ]
