# Generated by Django 4.1 on 2022-10-15 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "FuerzasMilitares",
            "0007_practicapoligono_militar_alter_poligono_cartuchos_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="poligono",
            name="militar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="poligono_militar",
                to="FuerzasMilitares.militar",
            ),
        ),
    ]
